### ISSUE TITLE
Fig 2.11 not in PDF document

### ISSUE THREAD

**Issue by cajwalsh** [cooplab/popgen-notes#12]
I was reading a previous version of this document when I noticed that in Section 2.3.1 that Figure 2.5 was referenced in the text as a schematic diagram but not displayed. I checked for updates, and in this new version it is now referred to in the same manner, but now as Figure 2.11 (on page 18, section 2.3.1), but still (as far as I can tell) not displayed in the PDF, captions also seem to skip from 2.10 to 2.12.

**Comment by cooplab** [comment]
Sorry the notes are currently in a state of flux as we were prepping a new version for our course. This should be fixed now, and they should be in good shape through to ~page 36.
