### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by tvkent** [cooplab/popgen-notes#16]
p.45 "birds blown of course" -> "birds blown off course"
though, of course the divine wind blew them off course to colonize new islands

**Comment by tvkent** [comment]
p.225 "prevent each other reach fixation" -> "prevent each other from reaching fixation"

**Comment by cooplab** [comment]
Thanks, Tyler. These have been corrected in the current pdfs, sorry stupidly I missed this for the new release. 

G
