### ISSUE TITLE
Table of contents issue

### ISSUE THREAD

**Issue by feuerbach** [cooplab/popgen-notes#19]
Cool book, looking forward to reading it!

There is a small issue with the built-in PDF table of contents (not the TOC on pp 5-6): the introduction to the mathematical concepts points to page 7 (i.e. the initial Introduction), and clicking on it does take you to page 7 instead of 245.

**Comment by cooplab** [comment]
Thanks for catching that. The pdfs on github have been updated.

Fixed by inserting "hypertexnames=false" into \hypersetup options as discussed here:
https://tex.stackexchange.com/questions/231361/table-of-contents-labels-not-directing-hyperlinks-to-correct-page
