### ISSUE TITLE
fix Fig. 12.8 axis labels and legend

### ISSUE THREAD

**Issue by arlin** [cooplab/popgen-notes#26]
- [x] currently the x axis ticks show N_e, but the axis label says log(N_e)
- [x] in the legend, change "passed 1" to "past 1"
- [x] in the legend, it would be clearer to to write 1 / (2N) instead of 1 / 2N 
- [ ] unless I am confused, the references to N in the y axis label and the legend should refer to N_e

**Comment by cooplab** [comment]
Fixed, thanks! So for the moment, I'm leaving these are N's instead of Ne, as I need to write a comment about when it is (and when it isn't) appropriate to use Ne in equations in fixation probabilities.
