### ISSUE TITLE
Remark on Summary Chapter 7

### ISSUE THREAD

**Issue by KathSe1984** [cooplab/popgen-notes#27]
Great Book. Thanks a lot for sharing.

I just noted there seems to be something wrong with the 2nd bullet point of the summary for chapter 7 (p. 142). There is an incomplete sentence fragment.

> **The additive genetic variance is** The proportion of pheno-typic variance is the narrow sense heritability [...]

**Comment by cooplab** [comment]
Thanks for catching this, fixed in live version of pdf.
