### ISSUE TITLE
problem with equation 116?

### ISSUE THREAD

**Issue by ecalfee** [cooplab/popgen-notes#7]
I think there's a mistake but I don't know what the correction would be. Chapter 4 "one-locus models of selection" in the paragraph above equation 116 (justifying this equation), p doesn't equal 1-q at time tao.

**Comment by cooplab** [comment]
OK that should be fixed now I changed it over to q_{\tau} = 1/N

**Comment by jjberg2** [comment]
Damn. You beat me by 10 seconds Graham.

Closing issue.
